version: '3.6'

services:
  data-science-toolbox:
    image: ${DOCKER_ENV_IMAGE}
    ports:
      - '${DOCKER_ENV_JUPYTER_PORT}:${DOCKER_ENV_JUPYTER_PORT}'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${DOCKER_ENV_VOLUME_HOST_PATH}:${DOCKER_ENV_VOLUME_CONTAINER_PATH}
    dns:
      - 8.8.8.8
    stdin_open: true
    tty: true
    entrypoint: -- 
