[build-system]
requires = [
	"setuptools",
	"versioneer-518",
	"wheel"
]
build-backend = "setuptools.build_meta"

[tool.black]
exclude = '''
_version.py
'''

# black compliance
[tool.isort]
profile = "black"
